### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by VoronVoronov** [romanzipp/Laravel-Twitch#91]
![image](https://user-images.githubusercontent.com/59320246/115486210-dd65e480-a25e-11eb-8424-a0181d340103.png)
I already wrote that eventsub is not confirmed. It turned out that secret is not transmitted

**Comment by VoronVoronov** [comment]
https://github.com/romanzipp/Laravel-Twitch/discussions/90

**Comment by romanzipp** [comment]
At first, always use **Issues** instead of discussions, those are two completely separate features. Please **do not post screenshots** of Code, I can not read a compressed line of JSON...

[Here are some guidelines on how to write issues](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f)

So what do you want me to do? Is your issues resolved?

**Comment by VoronVoronov** [comment]
I did everything as in the documentation, for creating a webhook eventsub, but failed everywhere. When decrypting the request, I saw that "secret" was not passed"

**Comment by VoronVoronov** [comment]
Even after specifying secret, the request is still sent without specifying secret.

**Comment by VoronVoronov** [comment]
Fixed the problem thanks to him https://github.com/romanzipp/Laravel-Twitch/issues/82
